### ISSUE TITLE
No module named 'nis' on Windows 10

### ISSUE THREAD

**Issue by EpicLPer** [dakhnod/fzfs#2]
Trying to run this Python script on Windows results in the following:

```
(venv) PS C:\Users\xxx\Downloads\fzfs-main> .\fzfs.py -d COM5 -m .\flipper_sd\
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\fzfs-main\fzfs.py", line 11, in <module>
    import flipper_api
  File "C:\Users\xxx\Downloads\fzfs-main\flipper_api.py", line 12, in <module>
    from flipperzero_protobuf_py.flipper_protobuf import ProtoFlipper
  File "C:\Users\xxx\Downloads\fzfs-main\flipperzero_protobuf_py\flipper_protobuf.py", line 3, in <module>
    from nis import match
ModuleNotFoundError: No module named 'nis'
```

**Comment by dakhnod** [comment]
TBH I'd be surprised if this worked on windows...

**Comment by EpicLPer** [comment]
I'm sadly not a programmer to test or try this properly, tho Windows theoretically does have Symlink functionality (if that's what this Python script even does, not sure) :)

Not sure if you'd be up for it to try and port it to Windows too, just found this script as a kind of "_I'm too lazy to take the SD Card out, lets see what other options there are_" :)

**Comment by dakhnod** [comment]
I'm happy you found this, unfortunate I don't have the means of supporting windows right now.

This script is using FUSE as a file system driver, not sure if that exists on windows.

Did you install anything using pip?

**Comment by EpicLPer** [comment]
The equivalent to FUSE would be WinFsp, which as example rclone also uses to provide virtual drives or symlinked folders. https://winfsp.dev/  

I only installed the required packages stated in the readme.

**Comment by ASoldo** [comment]
I have the same problem but "No module named 'tkinter'" is the error message.
```bash
❯ venv/bin/python3 fzfs.py -d /dev/ttyACM0 -m /home/user/flipper-zero
Traceback (most recent call last):
  File "fzfs.py", line 9, in <module>
    from turtle import back
  File "/usr/lib/python3.8/turtle.py", line 107, in <module>
    import tkinter as TK
ModuleNotFoundError: No module named 'tkinter'
```
How can I resolve it?
