### ISSUE TITLE
Not able to mount using BTLE

### ISSUE THREAD

**Issue by s1shed** [dakhnod/fzfs#9]
```
❯ python3 fzfs.py -a MACADDR -m /home/user/fzmount
Traceback (most recent call last):
  File "/home/user/src/fzfs/fzfs.py", line 63, in <module>
    main()
  File "/home/user/src/fzfs/fzfs.py", line 42, in main
    if not os.path.exists(args.serial_device):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

I tried the following to troubleshoot a bit
```python
import serial
import serial.tools.list_ports
import serial_ble
bluetooth = serial_ble.BLESerial(MACADDR, '19ed82ae-ed21-4c9d-4145-228e61fe0000', '19ed82ae-ed21-4c9d-4145-228e62fe0000')
print(bluetooth)
```

which yielded the following
```
Traceback (most recent call last):
  File "/home/user/src/fzfs/t.py", line 5, in <module>
    print(bluetooth)
  File "/home/user/.virtualenvs/fzfs/lib/python3.11/site-packages/serial/serialutil.py", line 532, in __repr__
    'rtscts={p.rtscts!r}, dsrdtr={p.dsrdtr!r})'.format(
                                                ^^^^^^^
AttributeError: 'BLESerial' object has no attribute 'is_open'. Did you mean: 'isOpen'?
```

Using the cable with my FZ works fine.

Please let me know if there's anything I can try to help debug this.

**Comment by dakhnod** [comment]
Hm, weird. Could this be a dependency issue? Did you install from requirements.txt?

**Comment by s1shed** [comment]
Yes, the dependencies were installed using `requirements.txt` 

OS: Debian Sid
Python 3.11.4


```
❯ pip3 list
Package       Version
------------- -------
async-timeout 4.0.2
bleak         0.17.0
dbus-fast     1.4.0
fusepy        3.0.1
numpy         1.23.3
pip           23.1.2
protobuf      4.21.6
pyserial      3.5
setuptools    67.8.0
wheel         0.38.4
```

**Comment by dakhnod** [comment]
Hey, I updated some dependencies. Could you try again?
